### ISSUE TITLE
all reads invalid

### ISSUE THREAD

**Issue by Yang990-sys** [adnaniazi/tailfinder#32]
hello,

I'm using tailfindr to find polyA/polyT tails for cDNA ，and my kit is SQK-PCS111,  but all reads  are invalid,
![image](https://user-images.githubusercontent.com/54176741/179729681-5be332a2-8831-407d-b128-ba3f7e3f7112.png)

I have re-basecalled my fast5 file with guppy : 

guppy_basecaller \
    --config dna_r9.4.1_450bps_flipflop.cfg \
    --input $INPUT \
    --save_path $OUTPUT \
    --recursive \
    --fast5_out \
    --hp_correct 1 \
    --disable_pings 1 \
    --enable_trimming 0 

and find tails with:

find_tails(fast5_dir = './test/',
           save_dir = './',
           csv_filename = 'cdna_tails2.csv',
           num_cores = 20,
           dna_datatype = 'pcr-dna',
           basecall_group ='Basecall_1D_001',
           save_plots = F)

Is this because primers are not specified ? Or other reasons? Thanks so much for your help !

**Comment by adnaniazi** [comment]
Hi,
Please remove dna_datatype = 'pcr-dna', from your command, and try again. Hopefully it would work.

Best,
Adnan

**Comment by Yang990-sys** [comment]
Thanks so much for your help. when dna_datatype = 'pcr-dna' is removed, I get 2715 valid reads in 4000 reads. Within these invalid reads,  895 reads still seems to be read_type:invalid ,345 reads is tail_is_valid:FALSE, and 45 reads is all blank. Is that a normal ratio?
![image](https://user-images.githubusercontent.com/54176741/179741375-10cf151a-14cc-4499-954a-03508b43cd33.png)
![image](https://user-images.githubusercontent.com/54176741/179741677-6fd4bdb9-3897-470d-a8d0-ecbdc4319d6e.png)
![image](https://user-images.githubusercontent.com/54176741/179741816-f9958b19-c702-42a7-8d4f-aeacfc8e0bea.png)

🙏🙏

**Comment by adnaniazi** [comment]
Yes, the number seems normal to me in my experience.

Adnan

**Comment by Yang990-sys** [comment]
Thanks a lot for your help !
